### ISSUE TITLE
Вывод расписания картинкой

### ISSUE THREAD

**Issue by degorychev** [teyhd/TimeTable_VKBot#6]
Скрипт на питоне готов, через пхп вывод адаптирован.
Необходимо дать пользователям выбор в каком виде они хотят получать расписание текстом или картинкой. (Отдельный пункт внутри настроек). И если пользователь просит присылать картинкой - запускать скрипт и результат работы скрипта отправлять пользователю.

**Comment by teyhd** [comment]
Почти готово
