### ISSUE TITLE
Вывод даты перед расписанием

### ISSUE THREAD

**Issue by degorychev** [teyhd/TimeTable_VKBot#7]
Сейчас дата выводится и это хорошо. Но она выводится последним сообщением, то есть - в конце, это не совсем удобно, Лучше сначала писать на какое число сейчас будет отправлено расписание, а затем само расписание.
Но это не так страшно, как следующее: В случае если в запрашиваемый день день пар нет, бот не присылает на какое число это расписание. Это приводит к тому, что человек пытается написать какую то дату, бот эту дату не распознает или распознает не правильно, пытается прислать расписание на совершенно другой день (когда пар нет), а человек даже не понимает что бот прислал "отсутствие пар" на другой день.

**Comment by teyhd** [comment]
Готово
